### ISSUE TITLE
Support JSON response

### ISSUE THREAD

**Issue by aibou** [aibou/scarecrow#2]
``` yaml
/:
  GET:
    - response:
        body:
          name: john
          age: 20
```

should return:

``` json
{ "name" : "john", "age" : 20 }
```
